export const DOCUMENT_FILTERS = [
  "All Documents",
  "Shared with Family",
  "Favorites",
  "Trash",
];

export const FOLDER_STYLE_COLORS = {
  blue: "bg-blue-500/20 text-blue-300 border-blue-500/40",
  amber: "bg-amber-500/20 text-amber-300 border-amber-500/40",
  emerald: "bg-emerald-500/20 text-emerald-300 border-emerald-500/40",
  rose: "bg-rose-500/20 text-rose-300 border-rose-500/40",
  violet: "bg-violet-500/20 text-violet-300 border-violet-500/40",
  slate: "bg-slate-500/20 text-slate-300 border-slate-500/40",
};

export const INITIAL_FOLDERS = [
  {
    id: "folder-passport",
    name: "Passport Scans",
    color: "blue",
    icon: "folder",
    files: [
      {
        id: "doc-passport-john",
        title: "Passport_Scan.pdf",
        fileType: "PDF",
        category: "Identity",
        uploadedAt: "2 days ago",
        sizeMb: 1.2,
      },
      {
        id: "doc-birth-cert",
        title: "Birth_Certificate.pdf",
        fileType: "PDF",
        category: "Identity",
        uploadedAt: "Sep 05, 2023",
        sizeMb: 0.8,
      },
      {
        id: "doc-passport-jane",
        title: "Passport_Copy_Jane.pdf",
        fileType: "PDF",
        category: "Identity",
        uploadedAt: "1 week ago",
        sizeMb: 1.9,
      },
      {
        id: "doc-visa",
        title: "Travel_Visa_Stamp.jpg",
        fileType: "IMAGE",
        category: "Travel",
        uploadedAt: "3 weeks ago",
        sizeMb: 8.5,
      },
    ],
  },
  {
    id: "folder-property",
    name: "Property Deeds",
    color: "amber",
    icon: "briefcase",
    files: [
      {
        id: "doc-title",
        title: "house_title_final.jpg",
        fileType: "IMAGE",
        category: "Property",
        uploadedAt: "Yesterday",
        sizeMb: 18.2,
      },
      {
        id: "doc-tax",
        title: "property_tax_receipt.pdf",
        fileType: "PDF",
        category: "Property",
        uploadedAt: "Aug 20, 2023",
        sizeMb: 27.6,
      },
    ],
  },
  {
    id: "folder-medical",
    name: "Medical Records",
    color: "emerald",
    icon: "heart",
    files: [
      {
        id: "doc-medical-q3",
        title: "medical_report_Q3.pdf",
        fileType: "PDF",
        category: "Medical",
        uploadedAt: "3 days ago",
        sizeMb: 1.1,
      },
      {
        id: "doc-vaccine",
        title: "vaccine_history.pdf",
        fileType: "PDF",
        category: "Medical",
        uploadedAt: "Oct 12, 2023",
        sizeMb: 0.9,
      },
      {
        id: "doc-lab",
        title: "lab_results_may.pdf",
        fileType: "PDF",
        category: "Medical",
        uploadedAt: "May 14, 2023",
        sizeMb: 0.5,
      },
      {
        id: "doc-prescription",
        title: "prescription_card.png",
        fileType: "IMAGE",
        category: "Medical",
        uploadedAt: "Apr 03, 2023",
        sizeMb: 0.4,
      },
      {
        id: "doc-policy-claim",
        title: "claim_references.docx",
        fileType: "DOCX",
        category: "Medical",
        uploadedAt: "Mar 10, 2023",
        sizeMb: 1.8,
      },
      {
        id: "doc-consultation",
        title: "consultation_notes.pdf",
        fileType: "PDF",
        category: "Medical",
        uploadedAt: "Jan 25, 2023",
        sizeMb: 3.5,
      },
      {
        id: "doc-medical-insurance",
        title: "medical_insurance.pdf",
        fileType: "PDF",
        category: "Medical",
        uploadedAt: "Dec 21, 2022",
        sizeMb: 0.3,
      },
      {
        id: "doc-medical-family",
        title: "family_history.pdf",
        fileType: "PDF",
        category: "Medical",
        uploadedAt: "Nov 13, 2022",
        sizeMb: 0.4,
      },
      {
        id: "doc-medical-ct",
        title: "ct_scan_report.pdf",
        fileType: "PDF",
        category: "Medical",
        uploadedAt: "Sep 17, 2022",
        sizeMb: 0.6,
      },
      {
        id: "doc-medical-blood",
        title: "bloodwork_annual.pdf",
        fileType: "PDF",
        category: "Medical",
        uploadedAt: "Jul 02, 2022",
        sizeMb: 0.2,
      },
      {
        id: "doc-medical-echo",
        title: "heart_echo_summary.pdf",
        fileType: "PDF",
        category: "Medical",
        uploadedAt: "May 08, 2022",
        sizeMb: 0.2,
      },
      {
        id: "doc-medical-release",
        title: "consent_release.pdf",
        fileType: "PDF",
        category: "Medical",
        uploadedAt: "Feb 11, 2022",
        sizeMb: 0.1,
      },
    ],
  },
  {
    id: "folder-insurance",
    name: "Insurance Policies",
    color: "rose",
    icon: "shield",
    files: [
      {
        id: "doc-travel-insurance",
        title: "travel_insurance.pdf",
        fileType: "PDF",
        category: "Insurance",
        uploadedAt: "1 week ago",
        sizeMb: 4.5,
      },
      {
        id: "doc-home-insurance",
        title: "home_insurance.jpg",
        fileType: "IMAGE",
        category: "Insurance",
        uploadedAt: "Oct 12, 2023",
        sizeMb: 4.5,
      },
      {
        id: "doc-auto-insurance",
        title: "auto_policy_2025.pdf",
        fileType: "PDF",
        category: "Insurance",
        uploadedAt: "Jan 15, 2025",
        sizeMb: 2.2,
      },
      {
        id: "doc-health-insurance",
        title: "health_plan_summary.pdf",
        fileType: "PDF",
        category: "Insurance",
        uploadedAt: "Nov 01, 2024",
        sizeMb: 1.4,
      },
      {
        id: "doc-life-insurance",
        title: "life_insurance_policy.pdf",
        fileType: "PDF",
        category: "Insurance",
        uploadedAt: "Aug 12, 2024",
        sizeMb: 1.5,
      },
    ],
  },
];
